/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
export type AnalyticsSummaryTopProductsItem = {
    productId: number;
    productName: string;
    totalSold: number;
    revenue: number;
};
//# sourceMappingURL=analyticsSummaryTopProductsItem.d.ts.map