/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
import type { AnalyticsSummaryOrdersByStatusItem } from './analyticsSummaryOrdersByStatusItem';
import type { AnalyticsSummaryTopProductsItem } from './analyticsSummaryTopProductsItem';
import type { Order } from './order';

export interface AnalyticsSummary {
  totalRevenue: number;
  totalOrders: number;
  totalProducts: number;
  totalUsers: number;
  pendingOrders: number;
  revenueToday: number;
  ordersToday: number;
  topProducts: AnalyticsSummaryTopProductsItem[];
  recentOrders: Order[];
  ordersByStatus: AnalyticsSummaryOrdersByStatusItem[];
}
