/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List products with filters
 */
export const listProductsQueryPageDefault = 1;
export const listProductsQueryLimitDefault = 20;

export const ListProductsQueryParams = zod.object({
  "category": zod.coerce.string().optional(),
  "search": zod.coerce.string().optional(),
  "minPrice": zod.coerce.number().optional(),
  "maxPrice": zod.coerce.number().optional(),
  "sizes": zod.coerce.string().optional(),
  "sort": zod.enum(['newest', 'price_asc', 'price_desc', 'popular', 'bestseller']).optional(),
  "tag": zod.coerce.string().optional(),
  "page": zod.coerce.number().default(listProductsQueryPageDefault),
  "limit": zod.coerce.number().default(listProductsQueryLimitDefault)
})

export const ListProductsResponse = zod.object({
  "products": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
})),
  "total": zod.number(),
  "page": zod.number(),
  "totalPages": zod.number()
})


/**
 * @summary Create a product (admin)
 */
export const CreateProductBody = zod.object({
  "name": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean().optional(),
  "isBestseller": zod.boolean().optional(),
  "isLimitedEdition": zod.boolean().optional(),
  "isNewArrival": zod.boolean().optional()
})


/**
 * @summary Get featured/homepage products grouped by section
 */
export const GetFeaturedProductsResponse = zod.object({
  "featured": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
})),
  "bestsellers": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
})),
  "newArrivals": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
})),
  "limitedEdition": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
})),
  "jantaFavorites": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
}))
})


/**
 * @summary Get product by ID
 */
export const GetProductParams = zod.object({
  "id": zod.coerce.number()
})

export const GetProductResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
})


/**
 * @summary Update product (admin)
 */
export const UpdateProductParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateProductBody = zod.object({
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "price": zod.number().optional(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()).optional(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()).optional(),
  "stock": zod.number().optional(),
  "tags": zod.array(zod.string()).optional(),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()).optional(),
  "isFeatured": zod.boolean().optional(),
  "isBestseller": zod.boolean().optional(),
  "isLimitedEdition": zod.boolean().optional(),
  "isNewArrival": zod.boolean().optional()
})

export const UpdateProductResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
})


/**
 * @summary Delete product (admin)
 */
export const DeleteProductParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary Get related products
 */
export const GetRelatedProductsParams = zod.object({
  "id": zod.coerce.number()
})

export const GetRelatedProductsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
})
export const GetRelatedProductsResponse = zod.array(GetRelatedProductsResponseItem)


/**
 * @summary List all categories
 */
export const ListCategoriesResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "image": zod.string().nullish(),
  "productCount": zod.number()
})
export const ListCategoriesResponse = zod.array(ListCategoriesResponseItem)


/**
 * @summary Create category (admin)
 */
export const CreateCategoryBody = zod.object({
  "name": zod.string(),
  "slug": zod.string(),
  "image": zod.string().nullish()
})


/**
 * @summary Register new user
 */
export const RegisterBody = zod.object({
  "email": zod.string(),
  "password": zod.string(),
  "name": zod.string(),
  "phone": zod.string().nullish()
})


/**
 * @summary Login user
 */
export const LoginBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
})

export const LoginResponse = zod.object({
  "user": zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "name": zod.string(),
  "phone": zod.string().nullish(),
  "isAdmin": zod.boolean(),
  "createdAt": zod.string()
}),
  "token": zod.string()
})


/**
 * @summary Logout user
 */
export const LogoutResponse = zod.object({
  "message": zod.string()
})


/**
 * @summary Get current user
 */
export const GetMeResponse = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "name": zod.string(),
  "phone": zod.string().nullish(),
  "isAdmin": zod.boolean(),
  "createdAt": zod.string()
})


/**
 * @summary Get cart (by session or user)
 */
export const GetCartResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
}),
  "size": zod.string(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "subtotal": zod.number(),
  "discount": zod.number(),
  "couponCode": zod.string().nullish(),
  "deliveryCharge": zod.number(),
  "total": zod.number(),
  "itemCount": zod.number()
})


/**
 * @summary Clear cart
 */
export const ClearCartResponse = zod.object({
  "message": zod.string()
})


/**
 * @summary Add item to cart
 */
export const AddToCartBody = zod.object({
  "productId": zod.number(),
  "size": zod.string(),
  "quantity": zod.number()
})

export const AddToCartResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
}),
  "size": zod.string(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "subtotal": zod.number(),
  "discount": zod.number(),
  "couponCode": zod.string().nullish(),
  "deliveryCharge": zod.number(),
  "total": zod.number(),
  "itemCount": zod.number()
})


/**
 * @summary Update cart item quantity
 */
export const UpdateCartItemParams = zod.object({
  "itemId": zod.coerce.number()
})

export const UpdateCartItemBody = zod.object({
  "quantity": zod.number()
})

export const UpdateCartItemResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
}),
  "size": zod.string(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "subtotal": zod.number(),
  "discount": zod.number(),
  "couponCode": zod.string().nullish(),
  "deliveryCharge": zod.number(),
  "total": zod.number(),
  "itemCount": zod.number()
})


/**
 * @summary Remove cart item
 */
export const RemoveCartItemParams = zod.object({
  "itemId": zod.coerce.number()
})

export const RemoveCartItemResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
}),
  "size": zod.string(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "subtotal": zod.number(),
  "discount": zod.number(),
  "couponCode": zod.string().nullish(),
  "deliveryCharge": zod.number(),
  "total": zod.number(),
  "itemCount": zod.number()
})


/**
 * @summary Apply coupon to cart
 */
export const ApplyCouponBody = zod.object({
  "code": zod.string()
})

export const ApplyCouponResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "product": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
}),
  "size": zod.string(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "subtotal": zod.number(),
  "discount": zod.number(),
  "couponCode": zod.string().nullish(),
  "deliveryCharge": zod.number(),
  "total": zod.number(),
  "itemCount": zod.number()
})


/**
 * @summary List current user's orders
 */
export const ListOrdersResponseItem = zod.object({
  "id": zod.number(),
  "orderNumber": zod.string(),
  "userId": zod.number().nullish(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "productName": zod.string(),
  "productImage": zod.string(),
  "size": zod.string(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "address": zod.object({
  "name": zod.string(),
  "phone": zod.string(),
  "line1": zod.string(),
  "line2": zod.string().nullish(),
  "city": zod.string(),
  "state": zod.string(),
  "pincode": zod.string()
}),
  "status": zod.string(),
  "paymentMethod": zod.string(),
  "paymentStatus": zod.string(),
  "subtotal": zod.number(),
  "discount": zod.number(),
  "deliveryCharge": zod.number(),
  "total": zod.number(),
  "couponCode": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListOrdersResponse = zod.array(ListOrdersResponseItem)


/**
 * @summary Place an order
 */
export const CreateOrderBody = zod.object({
  "address": zod.object({
  "name": zod.string(),
  "phone": zod.string(),
  "line1": zod.string(),
  "line2": zod.string().nullish(),
  "city": zod.string(),
  "state": zod.string(),
  "pincode": zod.string()
}),
  "paymentMethod": zod.enum(['cod', 'online']),
  "couponCode": zod.string().nullish(),
  "guestEmail": zod.string().nullish()
})


/**
 * @summary Get order by ID
 */
export const GetOrderParams = zod.object({
  "id": zod.coerce.number()
})

export const GetOrderResponse = zod.object({
  "id": zod.number(),
  "orderNumber": zod.string(),
  "userId": zod.number().nullish(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "productName": zod.string(),
  "productImage": zod.string(),
  "size": zod.string(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "address": zod.object({
  "name": zod.string(),
  "phone": zod.string(),
  "line1": zod.string(),
  "line2": zod.string().nullish(),
  "city": zod.string(),
  "state": zod.string(),
  "pincode": zod.string()
}),
  "status": zod.string(),
  "paymentMethod": zod.string(),
  "paymentStatus": zod.string(),
  "subtotal": zod.number(),
  "discount": zod.number(),
  "deliveryCharge": zod.number(),
  "total": zod.number(),
  "couponCode": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary List reviews for a product
 */
export const ListProductReviewsParams = zod.object({
  "id": zod.coerce.number()
})

export const ListProductReviewsResponseItem = zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "userId": zod.number(),
  "userName": zod.string(),
  "rating": zod.number(),
  "comment": zod.string(),
  "createdAt": zod.string()
})
export const ListProductReviewsResponse = zod.array(ListProductReviewsResponseItem)


/**
 * @summary Add a review
 */
export const CreateReviewParams = zod.object({
  "id": zod.coerce.number()
})

export const createReviewBodyRatingMax = 5;



export const CreateReviewBody = zod.object({
  "rating": zod.number().min(1).max(createReviewBodyRatingMax),
  "comment": zod.string()
})


/**
 * @summary Get user's wishlist
 */
export const GetWishlistResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "slug": zod.string(),
  "description": zod.string(),
  "price": zod.number(),
  "originalPrice": zod.number().nullish(),
  "images": zod.array(zod.string()),
  "category": zod.string(),
  "categoryId": zod.number().nullish(),
  "sizes": zod.array(zod.string()),
  "stock": zod.number(),
  "tags": zod.array(zod.string()),
  "fabric": zod.string().nullish(),
  "washCare": zod.string().nullish(),
  "highlights": zod.array(zod.string()),
  "isFeatured": zod.boolean(),
  "isBestseller": zod.boolean(),
  "isLimitedEdition": zod.boolean(),
  "isNewArrival": zod.boolean(),
  "averageRating": zod.number().nullish(),
  "reviewCount": zod.number(),
  "createdAt": zod.string()
})
export const GetWishlistResponse = zod.array(GetWishlistResponseItem)


/**
 * @summary Add product to wishlist
 */
export const AddToWishlistParams = zod.object({
  "productId": zod.coerce.number()
})

export const AddToWishlistResponse = zod.object({
  "message": zod.string()
})


/**
 * @summary Remove from wishlist
 */
export const RemoveFromWishlistParams = zod.object({
  "productId": zod.coerce.number()
})

export const RemoveFromWishlistResponse = zod.object({
  "message": zod.string()
})


/**
 * @summary List active banners
 */
export const ListBannersResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "image": zod.string(),
  "link": zod.string().nullish(),
  "cta": zod.string().nullish(),
  "position": zod.enum(['hero', 'promo', 'collection']),
  "isActive": zod.boolean(),
  "sortOrder": zod.number()
})
export const ListBannersResponse = zod.array(ListBannersResponseItem)


/**
 * @summary Create banner (admin)
 */
export const CreateBannerBody = zod.object({
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "image": zod.string(),
  "link": zod.string().nullish(),
  "cta": zod.string().nullish(),
  "position": zod.enum(['hero', 'promo', 'collection']),
  "isActive": zod.boolean().optional(),
  "sortOrder": zod.number().optional()
})


/**
 * @summary Update banner (admin)
 */
export const UpdateBannerParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateBannerBody = zod.object({
  "title": zod.string().optional(),
  "subtitle": zod.string().nullish(),
  "image": zod.string().optional(),
  "link": zod.string().nullish(),
  "cta": zod.string().nullish(),
  "isActive": zod.boolean().optional(),
  "sortOrder": zod.number().optional()
})

export const UpdateBannerResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "subtitle": zod.string().nullish(),
  "image": zod.string(),
  "link": zod.string().nullish(),
  "cta": zod.string().nullish(),
  "position": zod.enum(['hero', 'promo', 'collection']),
  "isActive": zod.boolean(),
  "sortOrder": zod.number()
})


/**
 * @summary Delete banner (admin)
 */
export const DeleteBannerParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List coupons (admin)
 */
export const ListCouponsResponseItem = zod.object({
  "id": zod.number(),
  "code": zod.string(),
  "discountType": zod.enum(['percentage', 'flat']),
  "discountValue": zod.number(),
  "minOrderAmount": zod.number().nullish(),
  "maxUses": zod.number().nullish(),
  "usedCount": zod.number(),
  "isActive": zod.boolean(),
  "expiresAt": zod.string().nullish()
})
export const ListCouponsResponse = zod.array(ListCouponsResponseItem)


/**
 * @summary Create coupon (admin)
 */
export const CreateCouponBody = zod.object({
  "code": zod.string(),
  "discountType": zod.enum(['percentage', 'flat']),
  "discountValue": zod.number(),
  "minOrderAmount": zod.number().nullish(),
  "maxUses": zod.number().nullish(),
  "isActive": zod.boolean().optional(),
  "expiresAt": zod.string().nullish()
})


/**
 * @summary List users (admin)
 */
export const ListUsersResponseItem = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "name": zod.string(),
  "phone": zod.string().nullish(),
  "isAdmin": zod.boolean(),
  "createdAt": zod.string()
})
export const ListUsersResponse = zod.array(ListUsersResponseItem)


/**
 * @summary Update current user profile
 */
export const UpdateProfileBody = zod.object({
  "name": zod.string().optional(),
  "phone": zod.string().nullish()
})

export const UpdateProfileResponse = zod.object({
  "id": zod.number(),
  "email": zod.string(),
  "name": zod.string(),
  "phone": zod.string().nullish(),
  "isAdmin": zod.boolean(),
  "createdAt": zod.string()
})


/**
 * @summary Get admin dashboard analytics
 */
export const GetAnalyticsResponse = zod.object({
  "totalRevenue": zod.number(),
  "totalOrders": zod.number(),
  "totalProducts": zod.number(),
  "totalUsers": zod.number(),
  "pendingOrders": zod.number(),
  "revenueToday": zod.number(),
  "ordersToday": zod.number(),
  "topProducts": zod.array(zod.object({
  "productId": zod.number(),
  "productName": zod.string(),
  "totalSold": zod.number(),
  "revenue": zod.number()
})),
  "recentOrders": zod.array(zod.object({
  "id": zod.number(),
  "orderNumber": zod.string(),
  "userId": zod.number().nullish(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "productName": zod.string(),
  "productImage": zod.string(),
  "size": zod.string(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "address": zod.object({
  "name": zod.string(),
  "phone": zod.string(),
  "line1": zod.string(),
  "line2": zod.string().nullish(),
  "city": zod.string(),
  "state": zod.string(),
  "pincode": zod.string()
}),
  "status": zod.string(),
  "paymentMethod": zod.string(),
  "paymentStatus": zod.string(),
  "subtotal": zod.number(),
  "discount": zod.number(),
  "deliveryCharge": zod.number(),
  "total": zod.number(),
  "couponCode": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "ordersByStatus": zod.array(zod.object({
  "status": zod.string(),
  "count": zod.number()
}))
})


/**
 * @summary List all orders (admin)
 */
export const listAllOrdersQueryPageDefault = 1;

export const ListAllOrdersQueryParams = zod.object({
  "status": zod.coerce.string().optional(),
  "page": zod.coerce.number().default(listAllOrdersQueryPageDefault)
})

export const ListAllOrdersResponse = zod.object({
  "orders": zod.array(zod.object({
  "id": zod.number(),
  "orderNumber": zod.string(),
  "userId": zod.number().nullish(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "productName": zod.string(),
  "productImage": zod.string(),
  "size": zod.string(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "address": zod.object({
  "name": zod.string(),
  "phone": zod.string(),
  "line1": zod.string(),
  "line2": zod.string().nullish(),
  "city": zod.string(),
  "state": zod.string(),
  "pincode": zod.string()
}),
  "status": zod.string(),
  "paymentMethod": zod.string(),
  "paymentStatus": zod.string(),
  "subtotal": zod.number(),
  "discount": zod.number(),
  "deliveryCharge": zod.number(),
  "total": zod.number(),
  "couponCode": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})),
  "total": zod.number(),
  "page": zod.number(),
  "totalPages": zod.number()
})


/**
 * @summary Update order status (admin)
 */
export const UpdateOrderStatusParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateOrderStatusBody = zod.object({
  "status": zod.enum(['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded'])
})

export const UpdateOrderStatusResponse = zod.object({
  "id": zod.number(),
  "orderNumber": zod.string(),
  "userId": zod.number().nullish(),
  "items": zod.array(zod.object({
  "id": zod.number(),
  "productId": zod.number(),
  "productName": zod.string(),
  "productImage": zod.string(),
  "size": zod.string(),
  "quantity": zod.number(),
  "price": zod.number()
})),
  "address": zod.object({
  "name": zod.string(),
  "phone": zod.string(),
  "line1": zod.string(),
  "line2": zod.string().nullish(),
  "city": zod.string(),
  "state": zod.string(),
  "pincode": zod.string()
}),
  "status": zod.string(),
  "paymentMethod": zod.string(),
  "paymentStatus": zod.string(),
  "subtotal": zod.number(),
  "discount": zod.number(),
  "deliveryCharge": zod.number(),
  "total": zod.number(),
  "couponCode": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Subscribe to newsletter
 */
export const SubscribeNewsletterBody = zod.object({
  "email": zod.string()
})

export const SubscribeNewsletterResponse = zod.object({
  "message": zod.string()
})


