/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface MessageResponse {
  message: string;
}

export interface Product {
  id: number;
  name: string;
  slug: string;
  description: string;
  price: number;
  /** @nullable */
  originalPrice?: number | null;
  images: string[];
  category: string;
  /** @nullable */
  categoryId?: number | null;
  sizes: string[];
  stock: number;
  tags: string[];
  /** @nullable */
  fabric?: string | null;
  /** @nullable */
  washCare?: string | null;
  highlights: string[];
  isFeatured: boolean;
  isBestseller: boolean;
  isLimitedEdition: boolean;
  isNewArrival: boolean;
  /** @nullable */
  averageRating?: number | null;
  reviewCount: number;
  createdAt: string;
}

export interface ProductInput {
  name: string;
  description: string;
  price: number;
  /** @nullable */
  originalPrice?: number | null;
  images: string[];
  /** @nullable */
  categoryId?: number | null;
  sizes: string[];
  stock: number;
  tags: string[];
  /** @nullable */
  fabric?: string | null;
  /** @nullable */
  washCare?: string | null;
  highlights: string[];
  isFeatured?: boolean;
  isBestseller?: boolean;
  isLimitedEdition?: boolean;
  isNewArrival?: boolean;
}

export interface ProductUpdate {
  name?: string;
  description?: string;
  price?: number;
  /** @nullable */
  originalPrice?: number | null;
  images?: string[];
  /** @nullable */
  categoryId?: number | null;
  sizes?: string[];
  stock?: number;
  tags?: string[];
  /** @nullable */
  fabric?: string | null;
  /** @nullable */
  washCare?: string | null;
  highlights?: string[];
  isFeatured?: boolean;
  isBestseller?: boolean;
  isLimitedEdition?: boolean;
  isNewArrival?: boolean;
}

export interface ProductListResponse {
  products: Product[];
  total: number;
  page: number;
  totalPages: number;
}

export interface FeaturedProductsResponse {
  featured: Product[];
  bestsellers: Product[];
  newArrivals: Product[];
  limitedEdition: Product[];
  jantaFavorites: Product[];
}

export interface Category {
  id: number;
  name: string;
  slug: string;
  /** @nullable */
  image?: string | null;
  productCount: number;
}

export interface CategoryInput {
  name: string;
  slug: string;
  /** @nullable */
  image?: string | null;
}

export interface User {
  id: number;
  email: string;
  name: string;
  /** @nullable */
  phone?: string | null;
  isAdmin: boolean;
  createdAt: string;
}

export interface RegisterInput {
  email: string;
  password: string;
  name: string;
  /** @nullable */
  phone?: string | null;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}

export interface ProfileUpdate {
  name?: string;
  /** @nullable */
  phone?: string | null;
}

export interface CartItem {
  id: number;
  productId: number;
  product: Product;
  size: string;
  quantity: number;
  price: number;
}

export interface Cart {
  items: CartItem[];
  subtotal: number;
  discount: number;
  /** @nullable */
  couponCode?: string | null;
  deliveryCharge: number;
  total: number;
  itemCount: number;
}

export interface CartItemInput {
  productId: number;
  size: string;
  quantity: number;
}

export interface CartItemUpdate {
  quantity: number;
}

export interface CouponApplyInput {
  code: string;
}

export interface OrderItem {
  id: number;
  productId: number;
  productName: string;
  productImage: string;
  size: string;
  quantity: number;
  price: number;
}

export interface OrderAddress {
  name: string;
  phone: string;
  line1: string;
  /** @nullable */
  line2?: string | null;
  city: string;
  state: string;
  pincode: string;
}

export interface Order {
  id: number;
  orderNumber: string;
  /** @nullable */
  userId?: number | null;
  items: OrderItem[];
  address: OrderAddress;
  status: string;
  paymentMethod: string;
  paymentStatus: string;
  subtotal: number;
  discount: number;
  deliveryCharge: number;
  total: number;
  /** @nullable */
  couponCode?: string | null;
  createdAt: string;
  updatedAt: string;
}

export type OrderInputPaymentMethod = typeof OrderInputPaymentMethod[keyof typeof OrderInputPaymentMethod];


export const OrderInputPaymentMethod = {
  cod: 'cod',
  online: 'online',
} as const;

export interface OrderInput {
  address: OrderAddress;
  paymentMethod: OrderInputPaymentMethod;
  /** @nullable */
  couponCode?: string | null;
  /** @nullable */
  guestEmail?: string | null;
}

export interface OrderListResponse {
  orders: Order[];
  total: number;
  page: number;
  totalPages: number;
}

export type OrderStatusUpdateStatus = typeof OrderStatusUpdateStatus[keyof typeof OrderStatusUpdateStatus];


export const OrderStatusUpdateStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  processing: 'processing',
  shipped: 'shipped',
  delivered: 'delivered',
  cancelled: 'cancelled',
  refunded: 'refunded',
} as const;

export interface OrderStatusUpdate {
  status: OrderStatusUpdateStatus;
}

export interface Review {
  id: number;
  productId: number;
  userId: number;
  userName: string;
  rating: number;
  comment: string;
  createdAt: string;
}

export interface ReviewInput {
  /**
     * @minimum 1
     * @maximum 5
     */
  rating: number;
  comment: string;
}

export type CouponDiscountType = typeof CouponDiscountType[keyof typeof CouponDiscountType];


export const CouponDiscountType = {
  percentage: 'percentage',
  flat: 'flat',
} as const;

export interface Coupon {
  id: number;
  code: string;
  discountType: CouponDiscountType;
  discountValue: number;
  /** @nullable */
  minOrderAmount?: number | null;
  /** @nullable */
  maxUses?: number | null;
  usedCount: number;
  isActive: boolean;
  /** @nullable */
  expiresAt?: string | null;
}

export type CouponInputDiscountType = typeof CouponInputDiscountType[keyof typeof CouponInputDiscountType];


export const CouponInputDiscountType = {
  percentage: 'percentage',
  flat: 'flat',
} as const;

export interface CouponInput {
  code: string;
  discountType: CouponInputDiscountType;
  discountValue: number;
  /** @nullable */
  minOrderAmount?: number | null;
  /** @nullable */
  maxUses?: number | null;
  isActive?: boolean;
  /** @nullable */
  expiresAt?: string | null;
}

export type BannerPosition = typeof BannerPosition[keyof typeof BannerPosition];


export const BannerPosition = {
  hero: 'hero',
  promo: 'promo',
  collection: 'collection',
} as const;

export interface Banner {
  id: number;
  title: string;
  /** @nullable */
  subtitle?: string | null;
  image: string;
  /** @nullable */
  link?: string | null;
  /** @nullable */
  cta?: string | null;
  position: BannerPosition;
  isActive: boolean;
  sortOrder: number;
}

export type BannerInputPosition = typeof BannerInputPosition[keyof typeof BannerInputPosition];


export const BannerInputPosition = {
  hero: 'hero',
  promo: 'promo',
  collection: 'collection',
} as const;

export interface BannerInput {
  title: string;
  /** @nullable */
  subtitle?: string | null;
  image: string;
  /** @nullable */
  link?: string | null;
  /** @nullable */
  cta?: string | null;
  position: BannerInputPosition;
  isActive?: boolean;
  sortOrder?: number;
}

export interface BannerUpdate {
  title?: string;
  /** @nullable */
  subtitle?: string | null;
  image?: string;
  /** @nullable */
  link?: string | null;
  /** @nullable */
  cta?: string | null;
  isActive?: boolean;
  sortOrder?: number;
}

export type AnalyticsSummaryTopProductsItem = {
  productId: number;
  productName: string;
  totalSold: number;
  revenue: number;
};

export type AnalyticsSummaryOrdersByStatusItem = {
  status: string;
  count: number;
};

export interface AnalyticsSummary {
  totalRevenue: number;
  totalOrders: number;
  totalProducts: number;
  totalUsers: number;
  pendingOrders: number;
  revenueToday: number;
  ordersToday: number;
  topProducts: AnalyticsSummaryTopProductsItem[];
  recentOrders: Order[];
  ordersByStatus: AnalyticsSummaryOrdersByStatusItem[];
}

export interface NewsletterInput {
  email: string;
}

export type ListProductsParams = {
category?: string;
search?: string;
minPrice?: number;
maxPrice?: number;
sizes?: string;
sort?: ListProductsSort;
tag?: string;
page?: number;
limit?: number;
};

export type ListProductsSort = typeof ListProductsSort[keyof typeof ListProductsSort];


export const ListProductsSort = {
  newest: 'newest',
  price_asc: 'price_asc',
  price_desc: 'price_desc',
  popular: 'popular',
  bestseller: 'bestseller',
} as const;

export type ListAllOrdersParams = {
status?: string;
page?: number;
};

