/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
export type BannerPosition = typeof BannerPosition[keyof typeof BannerPosition];
export declare const BannerPosition: {
    readonly hero: "hero";
    readonly promo: "promo";
    readonly collection: "collection";
};
//# sourceMappingURL=bannerPosition.d.ts.map