/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */

export type BannerInputPosition = typeof BannerInputPosition[keyof typeof BannerInputPosition];


export const BannerInputPosition = {
  hero: 'hero',
  promo: 'promo',
  collection: 'collection',
} as const;
