/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
export interface BannerUpdate {
    title?: string;
    /** @nullable */
    subtitle?: string | null;
    image?: string;
    /** @nullable */
    link?: string | null;
    /** @nullable */
    cta?: string | null;
    isActive?: boolean;
    sortOrder?: number;
}
//# sourceMappingURL=bannerUpdate.d.ts.map