/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
import type { CartItem } from './cartItem';

export interface Cart {
  items: CartItem[];
  subtotal: number;
  discount: number;
  /** @nullable */
  couponCode?: string | null;
  deliveryCharge: number;
  total: number;
  itemCount: number;
}
