/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
import type { Product } from './product';
export interface CartItem {
    id: number;
    productId: number;
    product: Product;
    size: string;
    quantity: number;
    price: number;
}
//# sourceMappingURL=cartItem.d.ts.map