/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
export interface Category {
    id: number;
    name: string;
    slug: string;
    /** @nullable */
    image?: string | null;
    productCount: number;
}
//# sourceMappingURL=category.d.ts.map