/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
import type { CouponDiscountType } from './couponDiscountType';
export interface Coupon {
    id: number;
    code: string;
    discountType: CouponDiscountType;
    discountValue: number;
    /** @nullable */
    minOrderAmount?: number | null;
    /** @nullable */
    maxUses?: number | null;
    usedCount: number;
    isActive: boolean;
    /** @nullable */
    expiresAt?: string | null;
}
//# sourceMappingURL=coupon.d.ts.map