/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */

export type CouponInputDiscountType = typeof CouponInputDiscountType[keyof typeof CouponInputDiscountType];


export const CouponInputDiscountType = {
  percentage: 'percentage',
  flat: 'flat',
} as const;
