/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
import type { CouponInputDiscountType } from './couponInputDiscountType';
export interface CouponInput {
    code: string;
    discountType: CouponInputDiscountType;
    discountValue: number;
    /** @nullable */
    minOrderAmount?: number | null;
    /** @nullable */
    maxUses?: number | null;
    isActive?: boolean;
    /** @nullable */
    expiresAt?: string | null;
}
//# sourceMappingURL=couponInput.d.ts.map