/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
export interface CouponApplyInput {
    code: string;
}
//# sourceMappingURL=couponApplyInput.d.ts.map