/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
import type { Product } from './product';
export interface FeaturedProductsResponse {
    featured: Product[];
    bestsellers: Product[];
    newArrivals: Product[];
    limitedEdition: Product[];
    jantaFavorites: Product[];
}
//# sourceMappingURL=featuredProductsResponse.d.ts.map