/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Cockroach Janta Party eCommerce API
 * OpenAPI spec version: 0.1.0
 */
export interface User {
    id: number;
    email: string;
    name: string;
    /** @nullable */
    phone?: string | null;
    isAdmin: boolean;
    createdAt: string;
}
//# sourceMappingURL=user.d.ts.map